version: "3"
services:
    app:
        build:
            context: ./docker
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - .:/var/www/html

    mysql:
        image: mysql:8
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
